version: '3.3'
services:
    esmr5:
        ports:
            - 8000:8000
        devices:
            - /dev/ttyUSB0
        image: 'sbkg0002/prometheus_esmr5:arm32v7-latest'
        build: esmr5
        restart: always
    grafana:
        ports:
            - 3000:3000
        image: grafana/grafana:latest
        restart: always
        volumes:
          - grafana_data:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
          - ./grafana/config.monitoring
    prometheus:
        ports:
          - '9090:9090'
        image: prom/prometheus:latest
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        restart: always

volumes:
    prometheus_data: {}
    grafana_data: {}
